Revert "Start using libarm-optimized-routines in libm."
This reverts commit 29378c049952eb5a96afaae00d633ca9547a1b0d.

Reason for revert: 
error: bionic/libm/Android.bp:6:1: "libm" depends on undefined module "libarm-optimized-routines"
ninja: build stopped: subcommand failed.
14:34:49 soong bootstrap failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1
make: Leaving directory '/mnt/intern1/julian/android/AICP/14.0'

Change-Id: I9a066d4ad5c7e62f76073f909e492fcccdeae4a7